
stages:
  - build
  - test

cmake-dev:
  stage: build
  script:
#   - git submodule update --init --recursive
    - sh ci/build_ci_1.sh debug
  only:
    - dev

cmake-master:
  stage: build
  script:
    - sh ci/build_ci_1.sh
  only:
    - master

make_install:
  stage: build
  script:
    - sh ci/build_ci_2.sh
  only:
    - dev
    - master

test:
  stage: test
  script:
    - sh ci/test_ci.sh
  only:
    - dev


#    - rm -rf /ci_build/terark-core/*
#    - cp -r pkg/* /ci_build/terark-core/
#    - cp -r src /ci_build/terark-core/
#    - rm -rf /ci_build/terark-core/src/**/*.cpp
#    - rm -rf /ci_build/terark-core/src/**/*.cc
